id: I08850172
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T14:25:24+00:00'
last_modified: '2022-06-08T09:03:22.935213+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18694
  title: མི་རིགས་ས་ཁོངས་རང་སྐྱོར་བྱེད་ཕྱོགས་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས་ཀྱི་དོན་འགྲེལ་དང་ཉེར་སྤྱོད་ཕྱོགས་སྟོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '8833':
      image_group_id: I8LS18696
      title: ''
      total_pages: 331
      order: 1
      base_file: 8833.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
