id: P009161
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS18694
  title: མི་རིགས་ས་ཁོངས་རང་སྐྱོར་བྱེད་ཕྱོགས་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས་ཀྱི་དོན་འགྲེལ་དང་ཉེར་སྤྱོད་ཕྱོགས་སྟོན།
  author: ''
  volumes:
    50b9502838d0453bbddb66e06aaf01c5:
      image_group_id: I8LS18696
      title: ''
      volume_number: 1
      total_pages: 331
      base_file: v001.txt
