id: opecha:P009161
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18694
  title: མི་རིགས་ས་ཁོངས་རང་སྐྱོར་བྱེད་ཕྱོགས་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས་ཀྱི་དོན་འགྲེལ་དང་ཉེར་སྤྱོད་ཕྱོགས་སྟོན།
  volume: ''
  author: ''
